In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv('1.02. Multiple linear regression.csv')

In [3]:
df.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [25]:
X = df[["SAT","Rand 1,2,3"]]
y = df["GPA"]


In [29]:
from sklearn.model_selection import train_test_split

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
from sklearn.linear_model import LinearRegression

In [31]:
lm = LinearRegression()

In [32]:
lm.fit(X,y)

LinearRegression()

In [33]:
lm.intercept_

0.29603261264909486

In [34]:
#predicting R squared

In [35]:
lm.score(X,y)

0.40668119528142843

In [36]:
# Formula for Adjusted R^2
# 𝑅2𝑎𝑑𝑗.=1−(1−𝑅2)∗𝑛−1𝑛−𝑝−

In [38]:
r2 = lm.score(X,y)

In [39]:
n = X.shape[0]
p = X.shape[1]

In [41]:
r2_adj = 1-(1-r2)*(n-1)/(n-p-1) #adjusted r square

In [42]:
r2_adj

0.39203134825134023

In [43]:
from sklearn.feature_selection import f_regression

In [45]:
f_regression(X,y) #p values and feature selection

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [46]:
p = f_regression(X,y)[1]

In [47]:
p.round(3)

array([0.   , 0.676])

In [48]:
reg_summary = pd.DataFrame(data = X.columns.values,columns=["coeff"])

In [49]:
reg_summary["coefficients"]=lm.coef_

In [50]:
reg_summary["P_values"]=p.round(3)

In [51]:
reg_summary

coeff  coefficients  P_values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676

In [54]:
#standardization 
from sklearn.preprocessing import StandardScaler

In [56]:
sm = StandardScaler()

In [58]:
sm.fit(X)

StandardScaler()

In [60]:
sm_trans = sm.transform(X)

In [61]:
sm_trans

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

In [62]:
lm.fit(sm_trans,y)

LinearRegression()

In [63]:
reg_summary = pd.DataFrame([['Bias'],['SAT'],['Rand 1,2,3']], columns=['Features'])
reg_summary['Weights'] = lm.intercept_, lm.coef_[0], lm.coef_[1]

In [64]:
reg_summary

Features   Weights
0        Bias  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

In [65]:
new_data = pd.DataFrame(data=[[1700,2],[1800,1]],columns=['SAT','Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [66]:
lm.predict(new_data)

array([295.39979563, 312.58821497])

In [68]:
new_data_scaled = sm.transform(new_data)

# Let's check the result
new_data_scaled

array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [69]:
lm.predict(new_data_scaled)
# The output is much more app

array([3.09051403, 3.26413803])